import Online.search_similar_code as SearchCode
import Online.context_generation as GenCKC
import Online.Get_TypeInference_Result.pipeline as GetResPipe
import Online.Get_TypeInference_Result.singal as GetResSig